#pragma once
#include "src/core/script/drawing/drawing.h"
#include "src/framework/option_types/icon_button.h"
#include "src/framework/option_types/button.h"
#include "src/hooking/hooking.h"

namespace Base::submenus::self {
    std::vector<std::pair<const char*, const char*>> scenarios_v = {
        {"Standing", "Standing"},
        {"Coffee", "WORLD_HUMAN_AA_COFFEE"},
        {"Smoke", "WORLD_HUMAN_AA_SMOKE"},
        {"Binoculars", "WORLD_HUMAN_BINOCULARS"},
        {"Freeway", "WORLD_HUMAN_BUM_FREEWAY"},
        {"Slumped", "WORLD_HUMAN_BUM_SLUMPED"},
        {"Bum Standing", "WORLD_HUMAN_BUM_STANDING"},
        {"Wash", "WORLD_HUMAN_BUM_WASH"},
        {"Car Park", "WORLD_HUMAN_CAR_PARK_ATTENDANT"},
        {"Cheering", "WORLD_HUMAN_CHEERING"},
        {"Clipboard", "WORLD_HUMAN_CLIPBOARD"},
        {"Clipboard (Facility)", "WORLD_HUMAN_CLIPBOARD_FACILITY"},
        {"Drill", "WORLD_HUMAN_CONST_DRILL"},
        {"Cop Idle", "WORLD_HUMAN_COP_IDLES"},
        {"Drinking", "WORLD_HUMAN_DRINKING"},
        {"Drinking (Facility)", "WORLD_HUMAN_DRINKING_FACILITY"},
        {"Drinking (Casino)", "WORLD_HUMAN_DRINKING_CASINO_TERRACE"},
        {"Drug Dealer", "WORLD_HUMAN_DRUG_DEALER"},
        {"Drug Dealer Hard", "WORLD_HUMAN_DRUG_DEALER_HARD"},
        {"Drug Field Rake", "WORLD_HUMAN_DRUG_FIELD_WORKERS_RAKE"},
        {"Drug Field Weeding", "WORLD_HUMAN_DRUG_FIELD_WORKERS_WEEDING"},
        {"Coke", "WORLD_HUMAN_DRUG_PROCESSORS_COKE"},
        {"Weed", "WORLD_HUMAN_DRUG_PROCESSORS_WEED"},
        {"Mobile Film Shocking", "WORLD_HUMAN_MOBILE_FILM_SHOCKING"},
        {"Leaf Blower", "WORLD_HUMAN_GARDENER_LEAF_BLOWER"},
        {"Plant", "WORLD_HUMAN_GARDENER_PLANT"},
        {"Golf Player", "WORLD_HUMAN_GOLF_PLAYER"},
        {"Guard Patrol", "WORLD_HUMAN_GUARD_PATROL"},
        {"Guard Stand", "WORLD_HUMAN_GUARD_STAND"},
        {"Guard Stand (Casino)", "WORLD_HUMAN_GUARD_STAND_CASINO"},
        {"Guard Stand (Clubhouse)", "WORLD_HUMAN_GUARD_STAND_CLUBHOUSE"},
        {"Guard Stand (Facility)", "WORLD_HUMAN_GUARD_STAND_FACILITY"},
        {"Guard Stand (Army)", "WORLD_HUMAN_GUARD_STAND_ARMY"},
        {"Hammering", "WORLD_HUMAN_HAMMERING"},
        {"Hang Out Street", "WORLD_HUMAN_HANG_OUT_STREET"},
        {"Hang Out Street (Clubhouse)", "WORLD_HUMAN_HANG_OUT_STREET_CLUBHOUSE"},
        {"Hiker", "WORLD_HUMAN_HIKER"},
        {"Hiker (Standing)", "WORLD_HUMAN_HIKER_STANDING"},
        {"Human Statue", "WORLD_HUMAN_HUMAN_STATUE"},
        {"Inspect Crouch", "WORLD_HUMAN_INSPECT_CROUCH"},
        {"Inspect Stand", "WORLD_HUMAN_INSPECT_STAND"},
        {"Janitor", "WORLD_HUMAN_JANITOR"},
        {"Jog", "WORLD_HUMAN_JOG"},
        {"Jog (Standing)", "WORLD_HUMAN_JOG_STANDING"},
        {"Leaning", "WORLD_HUMAN_LEANING"},
        {"Leaning (Casino)", "WORLD_HUMAN_LEANING_CASINO_TERRACE"},
        {"Maid", "WORLD_HUMAN_MAID_CLEAN"},
        {"Muscle Flex", "WORLD_HUMAN_MUSCLE_FLEX"},
        {"Muscle Flex Weights", "WORLD_HUMAN_MUSCLE_FREE_WEIGHTS"},
        {"Muscian", "WORLD_HUMAN_MUSICIAN"},
        {"Paparazzi", "WORLD_HUMAN_PAPARAZZI"},
        {"Partying", "WORLD_HUMAN_PARTYING"},
        {"Picnic", "WORLD_HUMAN_PICNIC"},
        {"Power Walker", "WORLD_HUMAN_POWER_WALKER"},
        {"Prostitue (High Class)", "WORLD_HUMAN_PROSTITUTE_HIGH_CLASS"},
        {"Prostitue (Low Class)", "WORLD_HUMAN_PROSTITUTE_LOW_CLASS"},
        {"Push Ups", "WORLD_HUMAN_PUSH_UPS"},
        {"Seat Ledge", "WORLD_HUMAN_SEAT_LEDGE"},
        {"Seat Ledge (Eating)", "WORLD_HUMAN_SEAT_LEDGE_EATING"},
        {"Seat Steps", "WORLD_HUMAN_SEAT_STEPS"},
        {"Seat Wall", "WORLD_HUMAN_SEAT_WALL"},
        {"Seat Wall (Eating)", "WORLD_HUMAN_SEAT_WALL_EATING"},
        {"Seat Wall (Tablet)", "WORLD_HUMAN_SEAT_WALL_TABLET"},
        {"Secruity Shine Torch", "WORLD_HUMAN_SECURITY_SHINE_TORCH"},
        {"Sit Ups", "WORLD_HUMAN_SIT_UPS"},
        {"Smoking", "WORLD_HUMAN_SMOKING"},
        {"Smoking (Clubhouse)", "WORLD_HUMAN_SMOKING_CLUBHOUSE"},
        {"Smoking Pot", "WORLD_HUMAN_SMOKING_POT"},
        {"Smoking Pot (Clubhouse)", "WORLD_HUMAN_SMOKING_POT_CLUBHOUSE"},
        {"Stand (Fire)", "WORLD_HUMAN_STAND_FIRE"},
        {"Stand (Fishing)", "WORLD_HUMAN_STAND_FISHING"},
        {"Stand (Impatient)", "WORLD_HUMAN_STAND_IMPATIENT"},
        {"Stand (Impatient Clubhouse)", "WORLD_HUMAN_STAND_IMPATIENT_CLUBHOUSE"},
        {"Stand (Impatient Facility)", "WORLD_HUMAN_STAND_IMPATIENT_FACILITY"},
        {"Stand (Impatient Upright)", "WORLD_HUMAN_STAND_IMPATIENT_UPRIGHT"},
        {"Stand (Impatient Upright Facility)", "WORLD_HUMAN_STAND_IMPATIENT_UPRIGHT_FACILITY"},
        {"Stand (Mobile)", "WORLD_HUMAN_STAND_MOBILE"},
        {"Stand (Mobile Clubhouse)", "WORLD_HUMAN_STAND_MOBILE_CLUBHOUSE"},
        {"Stand (Mobile Facility)", "WORLD_HUMAN_STAND_MOBILE_FACILITY"},
        {"Stand (Mobile Upright)", "WORLD_HUMAN_STAND_MOBILE_UPRIGHT"},
        {"Stand (Mobile Clubhouse)", "WORLD_HUMAN_STAND_MOBILE_UPRIGHT_CLUBHOUSE"},
        {"Strip Watch Stand", "WORLD_HUMAN_STRIP_WATCH_STAND"},
        {"Stupor", "WORLD_HUMAN_STUPOR"},
        {"Stupor (Clubhouse)", "WORLD_HUMAN_STUPOR_CLUBHOUSE"},
        {"Showroom", "WORLD_HUMAN_WINDOW_SHOP_BROWSE_SHOWROOM"},
        {"Sunbathe", "WORLD_HUMAN_SUNBATHE"},
        {"Sunbathe (Back)", "WORLD_HUMAN_SUNBATHE_BACK"},
        {"Superhero", "WORLD_HUMAN_SUPERHERO"},
        {"Swimming", "WORLD_HUMAN_SWIMMING"},
        {"Tennis Player", "WORLD_HUMAN_TENNIS_PLAYER"},
        {"Tourist Map", "WORLD_HUMAN_TOURIST_MAP"},
        {"Tourist Mobile", "WORLD_HUMAN_TOURIST_MOBILE"},
        {"Valet", "WORLD_HUMAN_VALET"},
        {"Vehicle Mechanic", "WORLD_HUMAN_VEHICLE_MECHANIC"},
        {"Welding", "WORLD_HUMAN_WELDING"},
        {"Shop Browse", "WORLD_HUMAN_WINDOW_SHOP_BROWSE"},
        {"Yoga", "WORLD_HUMAN_YOGA"},
        {"Walk", "Walk"},
        {"Walk (Facility)", "Walk_Facility"},
        {"Boar", "WORLD_BOAR_GRAZING"},
        {"Cat Sleeping (Ground)", "WORLD_CAT_SLEEPING_GROUND"},
        {"Cat Sleeping (Ledge)", "WORLD_CAT_SLEEPING_LEDGE"},
        {"Cow", "WORLD_COW_GRAZING"},
        {"Coyote (Growl)", "WORLD_COYOTE_HOWL"},
        {"Coyote (Rest)", "WORLD_COYOTE_REST"},
        {"Coyote (Wander)", "WORLD_COYOTE_WANDER"},
        {"Coyote (Walk)", "WORLD_COYOTE_WALK"},
        {"Chickenhawk (Feeding)", "WORLD_CHICKENHAWK_FEEDING"},
        {"Chickenhawk (Standing)", "WORLD_CHICKENHAWK_STANDING"},
        {"Cormorant (Standing)", "WORLD_CORMORANT_STANDING"},
        {"Crow (Feeding)", "WORLD_CROW_FEEDING"},
        {"Crow (Standing)", "WORLD_CROW_STANDING"},
        {"Deer", "WORLD_DEER_GRAZING"},
        {"Dog Barking (Rottweiler)", "WORLD_DOG_BARKING_ROTTWEILER"},
        {"Dog Barking (Retriever)", "WORLD_DOG_BARKING_RETRIEVER"},
        {"Dog Barking (Sheperd)", "WORLD_DOG_BARKING_SHEPHERD"},
        {"Dog Sitting (Rottweiler)", "WORLD_DOG_SITTING_ROTTWEILER"},
        {"Dog Sitting (Retriever)", "WORLD_DOG_SITTING_RETRIEVER"},
        {"Dog Sitting (Sheperd)", "WORLD_DOG_SITTING_SHEPHERD"},
        {"Dog Barking (Small)", "WORLD_DOG_BARKING_SMALL"},
        {"Dog Sitting (Small)", "WORLD_DOG_SITTING_SMALL"},
        {"Dolphin", "WORLD_DOLPHIN_SWIM"},
        {"Fish (Flee)", "WORLD_FISH_FLEE"},
        {"Fish (Idle)", "WORLD_FISH_IDLE"},
        {"Gull (Feeding)", "WORLD_GULL_FEEDING"},
        {"Gull (Standing)", "WORLD_GULL_STANDING"},
        {"Hen (Flee)", "WORLD_HEN_FLEE"},
        {"Hen (Pecking)", "WORLD_HEN_PECKING"},
        {"Hen (Standing)", "WORLD_HEN_STANDING"},
        {"Mountain Lion (Rest)", "WORLD_MOUNTAIN_LION_REST"},
        {"Mountain Lion (Wonder)", "WORLD_MOUNTAIN_LION_WANDER"},
        {"Orca", "WORLD_ORCA_SWIM"},
        {"Pig", "WORLD_PIG_GRAZING"},
        {"Pigeon (Feeding)", "WORLD_PIGEON_FEEDING"},
        {"Pigeon (Standing)", "WORLD_PIGEON_STANDING"},
        {"Rabbit (Eating)", "WORLD_RABBIT_EATING"},
        {"Rabbit (Flee)", "WORLD_RABBIT_FLEE"},
        {"Rat (Eating)", "WORLD_RATS_EATING"},
        {"Rat (Flee)", "WORLD_RATS_FLEEING"},
        {"Shark", "WORLD_SHARK_SWIM"},
        {"Hammerhead Shark", "WORLD_SHARK_HAMMERHEAD_SWIM"},
        {"Stingray", "WORLD_STINGRAY_SWIM"},
        {"Whale", "WORLD_WHALE_SWIM"},
        {"Drive", "DRIVE"},
        {"Vehicle Attractor", "WORLD_VEHICLE_ATTRACTOR"},
        {"Park", "PARK_VEHICLE"},
        {"Ambulance", "WORLD_VEHICLE_AMBULANCE"},
        {"BMX", "WORLD_VEHICLE_BICYCLE_BMX"},
        {"BMX (Ballas)", "WORLD_VEHICLE_BICYCLE_BMX_BALLAS"},
        {"BMX (Family)", "WORLD_VEHICLE_BICYCLE_BMX_FAMILY"},
        {"BMX (Harmony)", "WORLD_VEHICLE_BICYCLE_BMX_HARMONY"},
        {"BMX (Vagos)", "WORLD_VEHICLE_BICYCLE_BMX_VAGOS"},
        {"Boat Anchor", "WORLD_VEHICLE_BOAT_ANCHOR"},
        {"Boat Capsized", "WORLD_VEHICLE_BOAT_CAPSIZED"},
        {"Boat Chased", "WORLD_VEHICLE_BOAT_CHASE"},
        {"Boat Wrecked", "WORLD_VEHICLE_BOAT_WRECKED"},
        {"Bus", "WORLD_VEHICLE_BUSINESSMEN"},
        {"Car", "WORLD_VEHICLE_CAR_WAITING"},
        {"Car (Police)", "WORLD_VEHICLE_CONSTRUCTION_SOLO"},
        {"Convertible", "WORLD_VEHICLE_CONSTRUCTION_PASSENGERS"},
        {"Convertible (Police)", "WORLD_VEHICLE_CONSTRUCTION_PASSENGERS_HELI"},
        {"Convertible (Top Down)", "WORLD_VEHICLE_CONVERTIBLE_ROOF_UP"},
        {"Countryside Car", "WORLD_VEHICLE_CORONA"},
        {"Countryside Car (Top Down)", "WORLD_VEHICLE_CORONA_BARRACKS"},
        {"Countryside Car (Wrecked)", "WORLD_VEHICLE_CORONA_BOXVILLE"},
        {"Countryside Car (Wrecked Open)", "WORLD_VEHICLE_CORONA_BOXVILLE_OPEN"},
        {"Countryside Car (Wrecked)", "WORLD_VEHICLE_CORONA_BOXVILLE_WRECKED"},
        {"Cropduster", "WORLD_VEHICLE_COUNTRYSIDE"},
        {"Cropduster (Flying)", "WORLD_VEHICLE_COUNTRYSIDE_FLYING"},
        {"Crusher", "WORLD_VEHICLE_CRANE"},
        {"Crane Magnet", "WORLD_VEHICLE_CRANE_MAGNET"},
        {"Crane (Wrecked)", "WORLD_VEHICLE_CRANE_WRECKED"},
        {"Cruiser (Police)", "WORLD_VEHICLE_CRUISER"},
        {"Cruiser (Police Bike)", "WORLD_VEHICLE_FIRE_TRUCK"},
        {"Cruiser (Police Bike)", "WORLD_VEHICLE_FIRE_TRUCK_LADDER"},
        {"Cruiser (Police)", "WORLD_VEHICLE_FARM_TANNOY"}
    };
    void scenarios() {
        draw->button("Stop", [] {
            TASK::CLEAR_PED_TASKS_IMMEDIATELY(g_utils->self());
        });
        draw->seperator("List");
        for (auto& s : scenarios_v) {
            draw->button(s.first, [=] {
                TASK::TASK_START_SCENARIO_IN_PLACE(g_utils->self(), s.second, -1, true);
            });
        }
    }
}
